config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    validates :title, presence: true, length: { minimum: 6, maximum: 50 }
    validates :description, presence: true, length: { minimum: 10, maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles
  validates :username, presence: true, 
                       uniqueness: { case_sensitive: false }, 
                       length: { minimum: 4, maximum: 16 }
  EMAIL_REGEX =  /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
                    uniqueness: { case_sensitive: false }, 
                    length: { maximum: 105 }, 
                    format: {with: EMAIL_REGEX}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
		
	def show
        
    end

    def index
        @articles = Article.all
    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)
        @article.user = User.first
        if @article.save
            flash[:notice] = "Article was created successfully."
            redirect_to @article
        else
            render :new, status: :unprocessable_entity
        end
    end

    def update
        if  @article.update(article_params)
            flash[:notice] = "Article was updated successfully."
            redirect_to @article
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def edit
        
    end

    def destroy
       @article.destroy
       redirect_to articles_path
    end

    private
    
		def set_article
            @article = Article.find(params[:id])
		end

		def article_params
			params.require(:article).permit(:title, :description)
		end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
			@articles = Article.last(4).reverse
    end

    def about
    
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Account was created successfully"
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  
  end

  def update
    if  @user.update(user_params)
      flash[:notice] = "Account was updated successfully."
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<%= form_with scope: :article, url: articles_path, local: true do |f| %>
  <p>
      <%= f.label :title %><br/>
      <%= f.text_field :title %>
  </p>

  <p>
      <%= f.label :description %><br/>
      <%= f.text_area :description %>
  </p>
  
  <p>
      <%= f.submit %>
  </p>
<% end %>

app/views/articles/_formc.html.erb
<div class="container">
	<div class="row justify-content-center">	
		<div class="col-10">
			<%= render 'shared/errors', obj: @article %>
				<%= form_with scope: :article, class: "shadow p-3 mb-3 bg-placeholder rounded", url: articles_path, local: true do |f| %>
					<div class="row mb-3">
						<%= f.label :title, class: "col-2 col-form-label text-light fw-bold" %>
						<div class="col-10">
							<%= f.text_field :title, class: "form-control shadow-lg rounded", placeholder: "Title of article" %>
						</div>
					</div>

					<div class="row mb-3">
							<%= f.label :description, class: "col-2 col-form-label text-light fw-bold"  %>
						<div class="col-10">
							<%= f.text_area :description, rows: 10, class: "form-control shadow-lg rounded", placeholder: "Description of article" %>
						</div>
					</div>
					<div class="text-center">
						<%= f.submit "Post", class: "btn btn-primary btn-lg shadow-lg" %>
					</div>
				<% end %>
		</div>
		<%= link_to '[ Cancel ]', articles_path, class: "text-secondary text-center no-dec" %>
	</div>
</div>

app/views/articles/_forme.html.erb
<div class="container">
	<div class="row justify-content-center">	
		<div class="col-10">
			<%= render 'shared/errors', obj: @article %>
        <%= form_with(model: @article,  class: "shadow p-3 mb-3 bg-placeholder rounded", local: true) do |f| %>
					<div class="row mb-3">
						<%= f.label :title, class: "col-2 col-form-label text-light fw-bold" %>
						<div class="col-10">
							<%= f.text_field :title, class: "form-control shadow-lg rounded" %>
						</div>
					</div>

					<div class="row mb-3">
							<%= f.label :description, class: "col-2 col-form-label text-light fw-bold"  %>
						<div class="col-10">
							<%= f.text_area :description, rows: 10, class: "form-control shadow-lg rounded" %>
						</div>
					</div>
					<div class="text-center">
						<%= f.submit "Edit", class: "btn btn-primary btn-lg shadow-lg" %>
					</div>
				<% end %>
		</div>
		<%= link_to '[ Cancel ]', articles_path, class: "text-secondary text-center no-dec" %>
	</div>
</div>

app/views/articles/edit.html.erb
<link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
<style>
	div {
		font-family: 'Montserrat';
	}
</style>

<div class="pg-bg">
	<h1 class="p-4 text-center fw-bold">[Edit article]</h1>
	<%= render 'forme' %>

</div>

app/views/articles/index.html.erb
<link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
<style>
	div {
		font-family: 'Montserrat';
	}
</style>
<div class="pg-bg">
	<h1 class="text-decoration-line-through p-1 text-end">Articles</h1>
	<% @articles.each do |article| %>
		<div class="row justify-content-md-center">
			<div class="col-6 mt-4">	
				<div class="container">
					<div class="card text-center shadow-lg mb-5 rounded">
						<div class="card-header fst-italic">
							by <strong><%= article.user.username %></strong>
						</div>
						<div class="card-body">
							<h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-secondary no-dec" %></h5>
							<p class="card-text"><%= truncate(article.description, length: 100) %></p>
							<div class="justify-content-center" id="at-btns">
								<%= button_to 'View', article_path(article), method: :get, class: "btn btn-outline-success mx-1" %>
								<%= button_to 'Edit', edit_article_path(article), method: :get, class: "btn btn-outline-primary mx-1" %>
								<%= button_to 'Delete', article_path(article), method: :delete, form: {data: {turbo_confirm: "Are you sure you wanns delete this article?"}}, class: "btn btn-outline-danger mx-1" %>
							</div>
						</div>
						<div class="card-footer text-body-secondary">
							<small>Created at <%= time_ago_in_words(article.created_at) %> ago, edited <%= time_ago_in_words(article.updated_at) %> ago</small>
						</div>
					</div>
				</div>
			</div>	
		</div>
	<% end %>

app/views/articles/new.html.erb
<link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
<style>
	div {
		font-family: 'Montserrat';
	}
</style>

<div class="pg-bg">
	<h1 class="p-4 text-center fw-bold">[Create a new article]</h1>
	
	<div class="container">
		<%= render 'shared/errors', obj: @article %>
	</div>

	<%= render 'formc' %>
</div>

app/views/articles/show.html.erb
<link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
<style>
	div {
		font-family: 'Montserrat';
	}
</style>

<div class="pg-bg">
  <h2 class="text-center"><%= @article.title %></h2>
    <div class="row justify-content-md-center">
      <div class="col-6 mt-4">	
        <div class="container">
          <div class="card text-center shadow-lg mb-5 rounded">
            <div class="card-header fst-italic">
              by <strong><%= @article.user.username %></strong>
            </div>
            <div class="card-body">
              <p class="card-text"><%= @article.description %></p>
              <div class="justify-content-center" id="at-btns">
                <%= button_to 'Edit', edit_article_path(@article), method: :get, class: "btn btn-outline-primary mx-1" %>
                <%= button_to 'Delete', article_path(@article), method: :delete, form: {data: {turbo_confirm: "Are you sure you wanns delete this article?"}}, class: "btn btn-outline-danger mx-1" %>
              </div>
            </div>
            <div class="card-footer text-body-secondary">
              <small>Created at <%= time_ago_in_words(@article.created_at) %> ago, edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
            </div>
          </div>
        </div>
      </div>	
    </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="text-center text-lg-start text-white bg-violet">
  <!-- Section: Social media -->
  <section class="d-flex justify-content-between p-4">
    <div class="me-5">
      <span class="text-light" id="footer">Copyright &copy <%= link_to "fe1o", "https://github.com/fe1o", html_options = { target: "_blank", class: "font-monospace fei" } %></span>
    </div>
    <div>
      <a href="https://github.com/fe1o" target="_blank" class="text-white me-4">
        <i class="bi bi-github"></i>
      </a>
    </div>
  </section>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary navbar-dark">
  <div class="container-fluid">
    <%= link_to(image_tag('brand.png', id: "logo"), root_path, class: "navbar-brand") %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Articles", articles_path, class: "nav-link active" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle active" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            More
          </a>
          <ul class="dropdown-menu dropdown-menu-dark bg-violet">
            <li><%= link_to "About", about_path, class: "dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Contacts</a></li>
          </ul>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="..." aria-label="Search">
        <button class="btn btn-outline-light" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>fei'</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body style="background-color: #cec4d7;">
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
<style>
div {
  font-family: 'Montserrat';
}
</style>

<div class="pg-bg">
  <div class="container pt-3">
    <div class="bg-body-secondary shadow-lg p-5 rounded mx-3 text-wrap">
      <h1 class="display-4 fw-strong">[About me]</h1>
      <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
      <hr class="my-4">
      <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
<style>
  div {
    font-family: 'Montserrat';
  }
</style>

<div class="container">
  <div class="bg-violet text-light p-5 rounded mt-3 shadow" id="home-banner">
    <h1 class="display-4">A.K.A fe1o</h1>
    <p class="lead">A Ruby on Rails developer from Brazil.</p>
    <hr class="my-4">
    <%= button_to 'Sign up', signup_path, method: :get, class: "btn btn-success btn-lg" %>
  </div>
</div>

<div class="container" id="at-btns" style="padding-top: 8px;">
  <% @articles.each do |article| %>
    <div class="container my-3">
      <div class="card shadow-lg" style="width: 18rem; height: 13rem;">
        <div class="card-body">
          <h5 class="card-title fw-bold"><%= truncate(article.title, length: 20) %></h5>
          <p class="card-text"><%= truncate(article.description, length: 100) %></p>
          <%= button_to 'View', article_path(article), method: :get, class: "btn btn-primary btn-bottom" %>
          <small class="fst-italic date-bottom">| Created at <%= time_ago_in_words(article.created_at) %> ago |</small>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
	<div class="row justify-content-center">	
		<div class="col-7">
			<%= render 'shared/errors', obj: @user %>
        <%= form_with(model: @user,  class: "shadow p-3 mb-3 bg-placeholder rounded", local: true) do |f| %>
					<div class="row mb-3">
						<%= f.label :username, class: "col-2 col-form-label text-light fw-bold" %>
						<div class="col-7">
							<%= f.text_field :username, class: "form-control shadow-lg rounded" %>
						</div>
					</div>

					<div class="row mb-3">
							<%= f.label :email, class: "col-2 col-form-label text-light fw-bold"  %>
						<div class="col-7">
							<%= f.email_field :email, class: "form-control shadow-lg rounded" %>
						</div>
					</div>

          <div class="row mb-3">
            <%= f.label :password, class: "col-2 col-form-label text-light fw-bold"  %>
            <div class="col-7">
              <%= f.password_field :password, class: "form-control shadow-lg rounded" %>
            </div>
          </div>
					<div class="text-center">
						<%= f.submit(@user.new_record? ? "Sign up" : "Update", class: "btn btn-primary btn-lg shadow-lg") %>
					</div>
				<% end %>
		</div>
		<%= link_to '[ Cancel ]', articles_path, class: "text-secondary text-center no-dec" %>
	</div>
</div>

app/views/users/edit.html.erb
<link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
<style>
	div {
		font-family: 'Montserrat';
	}
</style>

<div class="pg-bg">
	<h1 class="p-4 text-center fw-bold">[Edit your profile]</h1>

	<%= render 'form' %>
</div>

app/views/users/new.html.erb
<link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
<style>
	div {
		font-family: 'Montserrat';
	}
</style>

<div class="pg-bg">
	<h1 class="p-4 text-center fw-bold">[Sign up]</h1>

	<%= render 'form' %>
</div>